### PR TITLE
fix issue #2 callback hell

### LINKED ISSUE #2: Callback hell 🔥
Currently, the code base uses callbacks everywhere, we should slowing (but soon) start the process of refactoring out all those callbacks and use async/await wherever is possible

### PR DESCRIPTION
**Pull request by FerrariAndrea**
- Rework callback to promise (async/await) finished and tested.
- WARN: some fixes are due to resolve other issues
- Removed some useless files
- Jest coverage: 95.27%
- Jest test passed, still 1 test failed cause of Zion query parser

Closes #2

### CODE REVIEW

File: DApp/src/component/DirectoriesCollector.ts [hunk 1]
```diff
@@ -66,75 +66,48 @@ export default class DirectoriesCollector implements IDirectoriesCollector{
...
+            }catch(err){
+                if(err instanceof Error){
+                    Logger.getInstance().addLog(componentName,"ResolveTD resolveToISourceArr error: "+ err.message,true);
+                }else{
+                    Logger.getInstance().addLog(componentName,"ResolveTD resolveToISourceArr error: "+ err,true);
                 }
             }
         }
-        
+        return ris;
```
Comment (relu91) [inline DApp/src/component/DirectoriesCollector.ts:92]: The refactored code does not contain any `await` call however it returns a Promise. What I also see is that `DirectoriesCollector` implements [IDirectoryCollettor](https://github.com/vaimee/desmo-dapp/blob/main/DApp/src/component/IDirectoriesCollector.ts) which is not updated in this PR. 

Questions:
1. Are you sure that you would need an asynchronous function for this functionality in `IDirectoryCollettor`
2. Double check that you don't have uncommitted changes

File: DApp/src/component/DirectoriesCollector.ts [hunk 2]
```diff
@@ -151,88 +124,69 @@ export default class DirectoriesCollector implements IDirectoriesCollector{
...
+            const ris = await axios.get(request_path);
+            if (ris.status === 200) {
+                //console.log("HIT---->C");//ok
+                //console.log(request_path, ris.data);
+                const json_to_filter = ris.data;
+                return await this.resolveToISourceArr(
+                    json_to_filter,
+                    parser,
+                    dirIndex,
+                )
```
Comment (relu91) [inline DApp/src/component/DirectoriesCollector.ts]: In this case you can even omit the `await` keyword

File: DApp/src/component/DirectoriesCollector.ts [hunk 3]
```diff
@@ -151,88 +124,69 @@ export default class DirectoriesCollector implements IDirectoriesCollector{
...
+                for(let ss =0;ss<iSources.length;ss++){
+                    if(iSources[ss].isPunished()){
+                        countPunishedSource++;
+                        break;
+                    }
+                }
+            }
+        }
+        Logger.getInstance().addLog(componentName,"Pre punished source: "+countPunishedSource+ "/"+count);
+        return ris;
```
Comment (relu91) [inline DApp/src/component/DirectoriesCollector.ts:173]: I am not seeing any await call in this function too. Are you sure it needs to by async?

File: DApp/src/component/DirectoriesCollector.ts [hunk 4]
```diff
@@ -151,88 +124,69 @@ export default class DirectoriesCollector implements IDirectoriesCollector{
...
+        return noTDs;
     }
 
-    collectDirs(
+    async collectDirs(
         sources: Array<string>,
         parser: IQueryParser,
-        cb: (resolvedSources: Map<string, Array<ISource>>) => void
-    ): void {
+        //cb: (resolvedSources: Map<string, Array<ISource>>) => void
```
Comment (relu91) [inline DApp/src/component/DirectoriesCollector.ts]: Commented code -> bad thing.

File: DApp/src/component/Worker.ts [hunk 5]
```diff
@@ -1,5 +1,5 @@
 import { promises as fsPromises } from 'fs';
-import QueryParser from "./queryParser";
+import QueryParser from "./QueryParser";
```
Comment (relu91) [inline DApp/src/component/Worker.ts:2]: The folder [componet](https://github.com/vaimee/desmo-dapp/tree/main/DApp/src/component) does not contain a file called `QueryParser.ts`. Neither I am seeing a change to rename that file. ARE YOU **SURE** that you don't have uncommitted changes???

File: DApp/src/component/Worker.ts [hunk 6]
```diff
@@ -125,51 +126,41 @@ export default class Worker implements IWorker {
...
-                  finalLoggerCall(err,true);
-                });
-              }
-
-              // }catch (e:any) {
-              //   this.err(e.message);
-              // }
+          const s = await collect(sourceValues);
+            //###########################Compute result
+            // try {
```
Comment (relu91) [inline DApp/src/component/Worker.ts]: Remove this poor thing.

File: DApp/src/component/Worker.ts [hunk 7]
```diff
@@ -125,51 +126,41 @@ export default class Worker implements IWorker {
...
+            this.logger.addLog(componentName,"computedJsonObj: " +JSON.stringify(computedJsonObj));
+
+            const finalLoggerCall =(msg:string, isErr:boolean)=>{
+                this.logger.addLog(componentName,msg,isErr);
+                this.logger.addLog(componentName,"DAPP ENDS");
+                this.logger.sendLogs(()=>{});
+            }
 
+            if (this.cb !== undefined) {
+              this.cb(computedJsonObj);
```
Comment (relu91) [inline DApp/src/component/Worker.ts:147]: HELL 🔥 . Is this still needed where does it come from?

File: DApp/src/component/consensus/dataCollector.ts [hunk 8]
```diff
@@ -100,19 +65,55 @@ export function collect(
...
-            });
+            }
+            await delay(Conf.T);
+            return await recursive();
         }
     }
-    setTimeout(recursive,Conf.T);
+
+    await delay(Conf.T);
+    return await recursive();
```
Comment (relu91) [inline DApp/src/component/consensus/dataCollector.ts:118]: Self reminder, discuss about this logic

File: DApp/src/component/queryParser.ts [hunk 9]
```diff
@@ -1,9 +1,7 @@
-
-import Types from "../const/Types";
 import IQuery, { IGeoAltitudeRange, IGeoCircle, IGeoPolygon, IPrefix, ITimeFilter, RequestedDataType } from "../model/IQuery";
 import IQueryParser from "./IQueryParser";
 import Config from "../const/Config";
-var jp = require('jsonpath');
+var jp = require('jsonpath'); //import jp from "jsonpath"; DO NOT WORK :(
```
Comment (relu91) [inline DApp/src/component/queryParser.ts:4]: I saw that you added jsonpath types, is this still not working?

**Review by relu91 — CHANGES_REQUESTED** [review]
General note, try not to commit uncommented code, it is a bad practice. I did not review the tests one to one cause we probably need to change them when #7 is done.

File: DApp/src/component/DirectoriesCollector.ts (hunk 1 above)
Comment (FerrariAndrea) [reply DApp/src/component/DirectoriesCollector.ts:92]: The await is on line 87:   `const reader = await this.resolveTD(tds[x]);`

File: DApp/src/component/DirectoriesCollector.ts (hunk 3 above)
Comment (FerrariAndrea) [reply DApp/src/component/DirectoriesCollector.ts:173]: The await is on line 165: `const tds = await this.getThingFromDir(realDirURL, indexDir, parser);`

File: DApp/src/component/Worker.ts (hunk 5 above)
Comment (FerrariAndrea) [reply DApp/src/component/Worker.ts:2]: I think that is an issue of Windows vs Unix file system. It is not the first time that I encounter that...
The problem is that, if I try to push the change of the renamed file from `queryParser` to `QueryParser`, that will not be pushed to github (indeed you can see the file name is still `queryParser` but on my local PC is `QueryParser`.
I use upper case for the first letter of the classes in that repo, so I prefer to have `QueryParser`.
I will try to resolve that issues later, for doing that I'm pretty sure, I need to:

1. remove the file QueryParser, commit and push
2. add QueryParser with the upper case first letter and then commit and push

In my experience that will fix the problem

File: DApp/src/component/Worker.ts (hunk 7 above)
Comment (FerrariAndrea) [reply DApp/src/component/Worker.ts:147]: That is needed for some tests, I'm not sure I should remove it.
In detail, if we are in a test that is using that worker, the test will set a callback used instead of the function this.err which will cause the `process.exit(1);`.

File: DApp/src/component/consensus/dataCollector.ts (hunk 8 above)
Comment (FerrariAndrea) [reply DApp/src/component/consensus/dataCollector.ts:118]: Yea, that is needed for the logic of the consensus algorithm on data.
You can interpret that like a sampler.

File: DApp/src/component/queryParser.ts (hunk 9 above)
Comment (FerrariAndrea) [reply DApp/src/component/queryParser.ts:4]: Yes, I tried more than one solution, and `var jp = require('jsonpath');` that work for jest and normal DApp run, `import jp from "jsonpath";` give me error on VSCode and do not work in both.
We can look at that together, and after the PR of issue #10, because in my opinion, that error is related to the TS compiler and the configuration file about it.  In the PR of issue #10, for example, I changed from `node-ts` to `tsc`, that can be might depend on (be influenced by) that too.

File: DApp/src/component/Worker.ts (hunk 5 above)
Comment (FerrariAndrea) [reply DApp/src/component/Worker.ts:2]: I confirm the new couple of commit fix that problem

Comment (relu91) [reply DApp/src/component/Worker.ts:2]: > I think that is an issue of Windows vs Unix file system. It is not the first time that I encounter that...
The problem is that, if I try to push the change of the renamed file from queryParser to QueryParser, that will not be pushed to github (indeed you can see the file name is still queryParser but on my local PC is QueryParser.
I use upper case for the first letter of the classes in that repo, so I prefer to have QueryParser.

I've not ever experienced such problems with Windows... but I glad that is now solved.

File: DApp/src/component/QueryParser.ts [hunk 10]
```diff
@@ -0,0 +1,291 @@
...
+    //         console.log("toResolve-->", this.getPrefixList());
+    //         if (this.getPrefixList() !== null) {
+    //             const tempList = this.getPrefixList();
+    //             for (var x in tempList) {
+
+    //             }
+    //         }
+    //     }
+    //     return null;
+    // }
```
Comment (relu91) [inline DApp/src/component/QueryParser.ts]: you forget to remove this

File: DApp/src/component/QueryParser.ts [hunk 11]
```diff
@@ -0,0 +1,291 @@
...
+                this.parsedQuery.timeFilter.interval.trim() == "" ||
+                this.parsedQuery.timeFilter.aggregation == null ||
+                this.parsedQuery.timeFilter.aggregation.trim() == "") { this.valid = false; return; }
+        }
+        */
+        /*
+        if (){
+            console.log ("invalid time filter"); this.valid = false; return; 
+ 
+        }
```
Comment (relu91) [inline DApp/src/component/QueryParser.ts]: and this

File: DApp/src/component/QueryParser.ts [hunk 12]
```diff
@@ -0,0 +1,291 @@
...
+        return this.parsedQuery.property.datatype === RequestedDataType.String;
+    }
+
+    getType(): number {
+        return this.parsedQuery.property.datatype;
+    }
+
+    // getParsedQuery(): IQuery {
+    //     return this.parsedQuery;
+    // }
```
Comment (relu91) [inline DApp/src/component/QueryParser.ts]: and this too

**Review by relu91 — CHANGES_REQUESTED** [review]
Ok almost ready to merge minor issues below

File: DApp/src/component/QueryParser.ts (hunk 10 above)
Comment (FerrariAndrea) [reply DApp/src/component/QueryParser.ts]: Yea sorry do not see it (because I remove it and then add it again for fix its name)

**Comment by relu91** [comment]
There are some changes in the package.json and package-lock.json that seems related to #10, can you remove unrelated changes?

**Comment by FerrariAndrea** [comment]
Pls have a look on that, is ok now?

**Review by relu91 — APPROVED** [review]

**Comment by relu91** [comment]
Let's move on :)
